env:
  browser: true
  es6: true
  jest: true
extends: 'airbnb'
plugins:
  - import
parser: babel-eslint
settings:
  import/resolver:
    node:
      moduleDirectory:
        - node_modules
        - src
