export const data1 = {
  children: [{
    name: 'Test',
    children: [{
      name: 'a',
      group: 'A',
      value: 1,
      state: true,
    }, {
      name: 'b',
      group: 'A',
      value: 1,
      state: false,
    }, {
      name: 'c',
      group: 'A',
      value: 1,
      state: true,
    }, {
      name: 'd',
      group: 'A',
      value: 1,
      state: true,
    }, {
      name: 'e',
      group: 'A',
      value: 1,
      state: true,
    }, {
      name: 'f',
      group: 'F',
      value: 1,
      state: false,
    }, {
      name: 'g',
      group: 'G',
      value: 1,
      state: true,
    }, {
      name: 'h',
      group: 'H',
      value: 1,
      state: false,
    }, {
      name: 'i',
      group: 'I',
      value: 1,
      state: true,
    }, {
      name: 'j',
      group: 'J',
      value: 1,
      state: true,
    }, {
      name: 'a',
      group: 'A',
      value: 1,
      state: true,
    }, {
      name: 'b',
      group: 'A',
      value: 1,
      state: false,
    }, {
      name: 'c',
      group: 'A',
      value: 1,
      state: true,
    }, {
      name: 'd',
      group: 'A',
      value: 1,
      state: true,
    }, {
      name: 'e',
      group: 'A',
      value: 1,
      state: true,
    }, {
      name: 'f',
      group: 'F',
      value: 1,
      state: false,
    }, {
      name: 'g',
      group: 'G',
      value: 1,
      state: true,
    }, {
      name: 'h',
      group: 'H',
      value: 1,
      state: false,
    }, {
      name: 'i',
      group: 'I',
      value: 1,
      state: true,
    }, {
      name: 'j',
      group: 'J',
      value: 1,
      state: true,
    }, {
      name: 'a',
      group: 'A',
      value: 1,
      state: true,
    }, {
      name: 'b',
      group: 'A',
      value: 1,
      state: false,
    }, {
      name: 'c',
      group: 'A',
      value: 1,
      state: true,
    }, {
      name: 'd',
      group: 'A',
      value: 1,
      state: true,
    }, {
      name: 'e',
      group: 'A',
      value: 1,
      state: true,
    }, {
      name: 'f',
      group: 'F',
      value: 1,
      state: false,
    }, {
      name: 'g',
      group: 'G',
      value: 1,
      state: true,
    }, {
      name: 'h',
      group: 'H',
      value: 1,
      state: false,
    }, {
      name: 'i',
      group: 'I',
      value: 1,
      state: true,
    }, {
      name: 'j',
      group: 'J',
      value: 1,
      state: true,
    }],
  }],
};

export const data2 = {
  children: [{
    name: 'APP 0',
    children: [{
      name: 'a',
      group: 'A',
      value: 1,
      state: true,
    }, {
      name: 'b',
      group: 'B',
      value: 1,
      state: false,
    }],
  }, {
    name: 'APP 1',
    children: [{
      name: 'c1',
      group: 'APP 1',
      value: 2,
      state: true,
    }, {
      name: 'c2',
      group: 'APP 1',
      value: 3,
      state: false,
    }, {
      name: 'c3',
      group: 'APP 1',
      value: 1,
      state: true,
    }],
  }, {
    name: 'APP 2',
    children: [{
      name: 'd',
      group: 'D',
      value: 1,
      state: true,
    }, {
      name: 'e',
      group: 'E',
      value: 1,
      state: true,
    }, {
      name: 'f',
      group: 'F',
      value: 1,
      state: false,
    }, {
      name: 'g',
      group: 'G',
      value: 1,
      state: true,
    }, {
      name: 'h',
      group: 'H',
      value: 1,
      state: false,
    }, {
      name: 'i',
      group: 'I',
      value: 1,
      state: true,
    }, {
      name: 'j',
      group: 'J',
      value: 1,
      state: true,
    }, {
      name: 'e',
      group: 'E',
      value: 1,
      state: true,
    }, {
      name: 'f',
      group: 'F',
      value: 1,
      state: false,
    }, {
      name: 'g',
      group: 'G',
      value: 1,
      state: true,
    }, {
      name: 'h',
      group: 'H',
      value: 1,
      state: false,
    }, {
      name: 'i',
      group: 'I',
      value: 1,
      state: true,
    }, {
      name: 'j',
      group: 'J',
      value: 1,
      state: true,
    }],
  }],
  name: 'Test',
};
